In [ ]:
!pip install numpy

In [ ]:
!pip install --upgrade pip

In [ ]:
%time [i for i in range(1000)]

In [1]:
import numpy as np
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(a.size)

9


In [4]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
b = np.ones((4,4,4))

In [6]:
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
c = np.ones((4,4), dtype=np.uint8)

In [8]:
print(c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
x = np.ones_like(a)

In [10]:
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
np_3d = np.arange(18).reshape(3,2,3)
print(np_3d)
print()
print(np_3d[2,:,1:])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]

[[13 14]
 [16 17]]


In [14]:
np_1 = np.array(([1,2],[3,4]))
np_2 = np.array(([1],[2]))
print(np_1)
print(np_2)

[[1 2]
 [3 4]]
[[1]
 [2]]


In [15]:
np_1 - np_2

array([[0, 1],
       [1, 2]])