In [1]:
import numpy as np

In [12]:
np_1 = np.random.randint(1,28, size=(3,3,3))
np_2 = np.random.randint(1,28, size=(3,3,3))
print(np_1)
print("-----------------")
print(np_2)

[[[ 8 23 21]
  [18 13 12]
  [10 12 22]]

 [[13  7 18]
  [23 18 21]
  [25  9 21]]

 [[11  6  4]
  [23  6 12]
  [11  5 21]]]
-----------------
[[[25  6 14]
  [ 6 15 23]
  [24 13 23]]

 [[ 7  7 25]
  [22 25 26]
  [17 18 23]]

 [[24  8 25]
  [18 22  2]
  [ 1 23 19]]]


# Oddiy tekshirish

In [14]:
np_1>np_2

array([[[False,  True,  True],
        [ True, False, False],
        [False, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[False, False, False],
        [ True, False,  True],
        [ True, False,  True]]])

In [17]:
np.where(np_1>np_2,np_1,np_2)

array([[[25, 23, 21],
        [18, 15, 23],
        [24, 13, 23]],

       [[13,  7, 25],
        [23, 25, 26],
        [25, 18, 23]],

       [[24,  8, 25],
        [23, 22, 12],
        [11, 23, 21]]])

# Funksiya bilan tekshirish

In [69]:
def np_3d(np_1,np_2):
    if np_1>np_2:
        return True
    return False

In [70]:
np.where(np_3d(np_1.all(),np_2.all()),"np_1","np_2")

array('np_2', dtype='<U4')

# Class bilan tekshirish

In [66]:
class NP_3d:
    def __init__(self,np_1,np_2):
        self.__np_1 = np_1
        self.__np_2 = np_2
    def solishtirish(self):
        if self.__np_1 > self.__np_2:
            return True
        return False

In [67]:
np1 = NP_3d(np_1.all(),np_2.all())

In [68]:
for i in range(len(np_1)):
    print(np.where(np1.solishtirish(),"np_1","np_2"), end=" ")

np_2 np_2 np_2 

In [90]:
class NP_3d1:
    def __init__(self,np_1,np_2):
        self.__np_1 = np_1
        self.__np_2 = np_2
    def __lt__(self):
        return True
    def __gt__(self):
        return False
    def kat(self):
        for i in range(len(np_1)):
            for j in range(len(np_1[i])):
                for k in range(len(np_1[i][j])):
                    if np_1[i][j][k].all()>np_2[i][j][k].all():
                        return True
        return False
for i in range(len(np_1)):
    for j in range(len(np_1[i])):
        for k in range(len(np_1[i][j])):
            np2 = NP_3d1(np_1[i][j][k].all(),np_2[i][j][k].all())
            print(np.where(np2.kat(),1,0), end=" ")

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [91]:
np_3 = np.random.randint(-14,13, size=(3,3,3))
np_4 = np.random.randint(-14,13, size=(3,3,3))
print(np_3)
print("-----------------")
print(np_4)

[[[  3   5   0]
  [  5  -5  -2]
  [-13   0   2]]

 [[ 10  -8 -13]
  [ -8 -12  -9]
  [  6  -2 -12]]

 [[-13   5  -8]
  [ -3   5   6]
  [ 10 -13 -11]]]
-----------------
[[[-13  12  -1]
  [ 12  -7  -3]
  [ -7   2  11]]

 [[ -3  10  -8]
  [-14 -12  -5]
  [ 11 -10  -5]]

 [[  0  -3   3]
  [  0 -13  -3]
  [  0   7  -4]]]


In [92]:
np.where(np_3>np_4,np_3,np_4)

array([[[  3,  12,   0],
        [ 12,  -5,  -2],
        [ -7,   2,  11]],

       [[ 10,  10,  -8],
        [ -8, -12,  -5],
        [ 11,  -2,  -5]],

       [[  0,   5,   3],
        [  0,   5,   6],
        [ 10,   7,  -4]]])

In [93]:
np_3 & np_4

array([[[  3,   4,   0],
        [  4,  -7,  -4],
        [-15,   0,   2]],

       [[  8,   8, -16],
        [-16, -12, -13],
        [  2, -10, -16]],

       [[  0,   5,   0],
        [  0,   1,   4],
        [  0,   3, -12]]])

In [94]:
np_3 >> 3

array([[[ 0,  0,  0],
        [ 0, -1, -1],
        [-2,  0,  0]],

       [[ 1, -1, -2],
        [-1, -2, -2],
        [ 0, -1, -2]],

       [[-2,  0, -1],
        [-1,  0,  0],
        [ 1, -2, -2]]], dtype=int32)

In [95]:
np_3 @ np_4

array([[[  21,    1,  -18],
        [-111,   91,  -12],
        [ 155, -152,   35]],

       [[ -61,  326,   25],
        [  93,  154,  169],
        [-122,  204,   22]],

       [[   0,  -82,  -22],
        [   0,  -14,  -48],
        [   0,   62,  113]]])