In [1]:
import re
print(re.__doc__)

Support for regular expressions (RE).

This module provides regular expression matching operations similar to
those found in Perl.  It supports both 8-bit and Unicode strings; both
the pattern and the strings being processed can contain null bytes and
characters outside the US ASCII range.

Regular expressions can contain both special and ordinary characters.
Most ordinary characters, like "A", "a", or "0", are the simplest
regular expressions; they simply match themselves.  You can
concatenate ordinary characters, so last matches the string 'last'.

The special characters are:
    "."      Matches any character except a newline.
    "^"      Matches the start of the string.
    "$"      Matches the end of the string or just before the newline at
             the end of the string.
    "*"      Matches 0 or more (greedy) repetitions of the preceding RE.
             Greedy means that it will match as many repetitions as possible.
    "+"      Matches 1 or more (greedy) repetitions of t

In [2]:
import re
sana = input("Sana(dd-mm-yyyy):")
if re.match(r"([0-2]{1}[0-9]|30|31){1}-(0[0-9]|10|11|12){1}-2[0-1][0-9]{2}", sana):
    print("To'g'ri", re.match(r"([0-2]{1}[0-9]|30|31){1}-(0[0-9]|10|11|12){1}-2[0-1][0-9]{2}", sana))
else:
    print("Sana xato kiritildi")

Sana(dd-mm-yyyy):23.01.1999
Sana xato kiritildi


In [3]:
# Kabisa yili
import re
sana = input("Sana(dd-mm-yyyy):")
#             |------------------------------ 31 kun ---------------------------------------|-------------------------- 30 kun -----------------------------------|----------------------- 28 kun ---------------------------|-------------------------------------------------------- 29 kun --------------------------------------------------------|
if re.match(r"((?:0[1-9]|[1-2]{1}[0-9]|30|31){1}-(?:0[13578]|10|12){1}-(?:19|20|21)[0-9]{2}$|(?:0[1-9]|[1-2]{1}[0-9]|30){1}-(?:0[469]|11){1}-(?:19|20|21)[0-9]{2}$|(?:0[1-9]|1{1}[0-9]{1}|2[0-8]{1})-02-(?:19|20|21)[0-9]{2}$|29-02-(?:(?:20[02468]{1}[048]{1}$|[13579]{1}[26]{1}$)|(?:(?:19|21)(?:(?:[02468]{1}[48]{1}$|[2468]{1}0)|[13579]{1}[26]{1}$))))", sana):
    print("To'g'ri")
else:
    print("Sana xato kiritildi")

Sana(dd-mm-yyyy):23.01.1999
Sana xato kiritildi


In [4]:
# ID karta
import re
ID = input("ID:")
if re.match(r"[A-Z]{2}[0-9]{7}$", ID):
    print("To'g'ri", re.match(r"[A-Z]{2}[0-9]{7}", ID))
else:
    print("ID karta xato kiritildi")

ID:123
ID karta xato kiritildi


In [1]:
import re
tel = input()
if re.match(r"\+\(998\) [0-9]{2} [0-9]{3}-[0-9]{2}-[0-9]{2}$", tel):
    print(1)
else:
    print(0)

+(998) 93 745-87-82
1


In [3]:
import re
matn = "Qad. Eronda yil 365kunli (12 oy 30 kundan_ va yana qo'shimcha 5kun) bo'lib, har 120-yilda bitta qo'shimcha oy kiritilgan. Umar Xayyom kalendarida har 33 yilning 8 yili (4, 8, 12, 16, 20, 24, 28 va 33-yillari) Kabisa yil hisoblanadi. Bunda har 4500-yilda bir sutkaga teng xato yig'iladi. Bu esa hozir qo'llaniladigan Grigoriy kalendaridan ham aniqroq(q. Kalendar)."
print(re.findall(r"[a-zA-Z0-9']+", matn))

['Qad', 'Eronda', 'yil', '365kunli', '12', 'oy', '30', 'kundan', 'va', 'yana', "qo'shimcha", '5kun', "bo'lib", 'har', '120', 'yilda', 'bitta', "qo'shimcha", 'oy', 'kiritilgan', 'Umar', 'Xayyom', 'kalendarida', 'har', '33', 'yilning', '8', 'yili', '4', '8', '12', '16', '20', '24', '28', 'va', '33', 'yillari', 'Kabisa', 'yil', 'hisoblanadi', 'Bunda', 'har', '4500', 'yilda', 'bir', 'sutkaga', 'teng', 'xato', "yig'iladi", 'Bu', 'esa', 'hozir', "qo'llaniladigan", 'Grigoriy', 'kalendaridan', 'ham', 'aniqroq', 'q', 'Kalendar']


In [142]:
import re
matn = input("Matn: ")

suzlar = {
    "sentabr":"сентябр", 
    "oktabr":"октябр", 
    "budjet":"бюджет", 
    "seziy":"цезий", 
    "seytnot":"цейтнот", 
    "sellofan":"целлофан", 
    "sellyuloza":"целлюлоза", 
    "selsiy":"целсий", 
    "sement":"цемент", 
    "senzor":"цензор", 
    "senzura":"цензура", 
    "sentner":"центер", 
    "sex":"цех", 
    "setse":"цетсе", 
    "sivilizatsiya":"цивилизация", 
    "sikl":"цикл", 
    "siklon":"циликон", 
    "silindr":"цилиндр", 
    "silindrik":"цилиндрик", 
    "silindrsimon":"цилиндрсимон", 
    "sirk":"цирк", 
    "sirkul":"циркул", 
    "sisterna":"цистерна", 
    "sitrus":"цитрус", 
}
birikmalar = {
    "ya":"я",  "Ya":"Я",  "YA":"Я",
    "yu":"ю",  "Yu":"Ю",  "YU":"Ю",
    "ch":"ч",  "Ch":"Ч",  "CH":"Ч",
    "sh":"ш",  "Sh":"Ш",  "SH":"Ш",
    "ye":"е",  "Ye":"Е",  "YE":"Е",
    "o'":"ў",  "O'":"Ў",
    "g'":"ғ",  "G'":"Ғ",
    "ts":"ц",
}
harflar = {
    "a":"а",  "A":"А",
    "b":"б",  "B":"Б",
    "d":"д",  "D":"Д",
    "e":"е",  "E":"Е",
    "f":"ф",  "F":"Ф",
    "g":"г",  "G":"Г",
    "h":"ҳ",  "H":"Ҳ",
    "i":"и",  "I":"И",
    "j":"ж",  "J":"Ж",
    "k":"к",  "K":"К",
    "l":"л",  "L":"Л",
    "m":"м",  "M":"М",
    "n":"н",  "N":"Н",
    "o":"о",  "O":"О",
    "p":"п",  "P":"П",
    "q":"қ",  "Q":"Қ",
    "r":"р",  "R":"Р",
    "s":"с",  "S":"С",
    "t":"т",  "T":"Т",
    "u":"у",  "U":"У",
    "v":"в",  "V":"В",
    "x":"х",  "X":"Х",
    "y":"й",  "Y":"Й",
    "z":"з",  "Z":"З",
    "'":"ъ"
}

def lot_kir(matn, suzlar,harflar, birikmalar):
    lower_matn = matn.lower()                              # Matnni kichik harflarga o'tkazadi
    text = re.findall(r"[a-z']+", lower_matn)              # Matndagi so'zlarni topadi
    suz = []
# Dictni listga o'tkazadi
    for m in suzlar.keys():
        suz.append(m)
    birikma = []
    for n in birikmalar.keys():
        birikma.append(n)
    for j in range(len(text)):
# Matndan maxsus so'zlarni kirillga o'tkazadi
        for i in range(len(suz)):
            if re.match(suz[i], text[j]):
                idx = text.index(suz[i])
                text.insert(idx, suzlar.get(suz[i]))
                text.pop(idx+1)       
        else:
# Matndan so'z birikmalarini kirillga o'tkazadi
            asosiy = ""
            for i in range(len(birikma)):
                if re.match(birikma[i], text[j]):
                    asosiy += birikmalar.get(birikma[i])
                    idx = i+1
# Qolgan harflarni kirillga o'tkazadi
            if re.match(r"[a-zA-Z]+", text[j]):
                if len(asosiy)==0:
                    for k in text[j]:
                        asosiy += harflar.get(k)
                else:
                    for k in text[j][2:]:
                        asosiy += harflar.get(k)
                text.insert(j, asosiy)
                text.pop(j+1)
    return " ".join(text)

print(lot_kir(matn,suzlar, harflar, birikmalar))

Matn: salom
салом


In [13]:
import re
matn = input("Matn: ")

suzlar = {
    "sentabr":"сентябр", 
    "oktabr":"октябр", 
    "budjet":"бюджет", 
    "seziy":"цезий", 
    "seytnot":"цейтнот", 
    "sellofan":"целлофан", 
    "sellyuloza":"целлюлоза", 
    "selsiy":"целсий", 
    "sement":"цемент", 
    "senzor":"цензор", 
    "senzura":"цензура", 
    "sentner":"центер", 
    "sex":"цех", 
    "setse":"цетсе", 
    "sivilizatsiya":"цивилизация", 
    "sikl":"цикл", 
    "siklon":"циликон", 
    "silindr":"цилиндр", 
    "silindrik":"цилиндрик", 
    "silindrsimon":"цилиндрсимон", 
    "sirk":"цирк", 
    "sirkul":"циркул", 
    "sisterna":"цистерна", 
    "sitrus":"цитрус", 
}
birikmalar = {
    "ya":"я",  "Ya":"Я",  "YA":"Я",
    "yu":"ю",  "Yu":"Ю",  "YU":"Ю",
    "ch":"ч",  "Ch":"Ч",  "CH":"Ч",
    "sh":"ш",  "Sh":"Ш",  "SH":"Ш",
    "ye":"е",  "Ye":"Е",  "YE":"Е",
    "o'":"ў",  "O'":"Ў",
    "g'":"ғ",  "G'":"Ғ",
    "ts":"ц",
}
harflar = {
    "a":"а",  "A":"А",
    "b":"б",  "B":"Б",
    "d":"д",  "D":"Д",
    "e":"е",  "E":"Е",
    "f":"ф",  "F":"Ф",
    "g":"г",  "G":"Г",
    "h":"ҳ",  "H":"Ҳ",
    "i":"и",  "I":"И",
    "j":"ж",  "J":"Ж",
    "k":"к",  "K":"К",
    "l":"л",  "L":"Л",
    "m":"м",  "M":"М",
    "n":"н",  "N":"Н",
    "o":"о",  "O":"О",
    "p":"п",  "P":"П",
    "q":"қ",  "Q":"Қ",
    "r":"р",  "R":"Р",
    "s":"с",  "S":"С",
    "t":"т",  "T":"Т",
    "u":"у",  "U":"У",
    "v":"в",  "V":"В",
    "x":"х",  "X":"Х",
    "y":"й",  "Y":"Й",
    "z":"з",  "Z":"З",
    "'":"ъ"
}
suz = []
for m in suzlar.keys():
        suz.append(m)
x = True
for i in range(len(suz)):
    text = re.sub(suz[i],suzlar.get(suz[i]),matn)
print(text)

Matn: sirk
sirk


In [6]:
print(re.sub(r'\d\d\.\d\d\.\d{4}', 
             r'DD.MM.YYYY', 
             r'Эта строка написана 19.01.2018, а могла бы и 01.09.2017')) 

Эта строка написана DD.MM.YYYY, а могла бы и DD.MM.YYYY


# OOP

In [6]:
class Pul_birlik:
    umumiy_pul = "Dollar"
    def __init__(self, pul):
        self.pul_birlik = pul
    def voz_kechish(self):
        self.umumiy_pul = self.pul_birlik
        
uzbekistan = Pul_birlik("So'm")
print(uzbekistan.umumiy_pul)
print(uzbekistan.pul_birlik)
uzbekistan.voz_kechish()
print(uzbekistan.umumiy_pul)
print(uzbekistan.pul_birlik)

Dollar
So'm
So'm
So'm


In [7]:
import re
from datetime import date
viloyatlar = ["Toshkent", "Andijon", "Farg'ona", "Namangan", "Sirdaryo", "Jizzax", "Samarqand", "Qashqadaryo",
             "Surxondaryo", "Navoiy", "Buxoro", "Xorazm", "Qoraqalpog'iston"]

class Talaba:
    def __init__(self,ism,fam,t_yil,kir_yil, vil, fak):
        self.ism = ism
        self.fam = fam
        self.t_yil = t_yil
        self.kir_yil = kir_yil
        self.vil = vil
        self.fak = fak
        hozir = date.today()
        self.kurs = hozir.year - kir_yil
    def kurs_qoldir(self):
        if self.kurs > 1:
            self.kurs -= 1
        else:
            self.kurs = 1
    def kurs_kutar(self):
        if self.kurs < 4:
            self.kurs += 1
        else:
            self.kurs = 4
    def ism_uzgar(self):
        self.ism = input("Ism: ")
    def fam_uzgar(self):
        self.fam = input("Familiya: ")
    # Talaba ma'lumotlari
    def mal(self):
        if 0 < self.kurs < 5:
            return f"\n{self.ism} {self.fam} {self.t_yil} yilda {self.vil}da tug'ilgan. {self.fak} fakultetining {self.kurs} kurs talabasi."
        else:
            return f"\n{self.ism} {self.fam} {self.t_yil} yilda {self.vil}da tug'ilgan. {self.fak} fakultetini {self.kurs-4} yil oldin bitirgan"
# Menyu
a = True
while a:
    menu = input(">>> Buyruqlar (new, kurs_kutar, kurs_qoldir, ism_uzgar, fam_uzgar, info, off): ")
    # Talaba ma'lumotlarini kiritish
    if menu == "new":
        x = True
        while x:
            isfa = r"[A-Z]{1}[a-z']+$"
            yil = r"(19|20)[0-9]{2}"
            ism = input(">>> Ism: ")
            while not re.match(isfa, ism):
                ism = input(">>> Ism: ")
            fam = input(">>> Familiya: ")
            while not re.match(isfa, fam):
                fam = input(">>> Familiya: ")
            t_yil = int(input(">>> Tug'ilgan yil: "))
            while not re.match(yil, str(t_yil)):
                t_yil = int(input(">>> Tug'ilgan yil: "))
            vil = input(">>> Viloyati: ")
            while vil not in viloyatlar:
                vil = input(">>> Viloyati: ")
            fak = input(">>> Fakultet: ")
            while not re.match(isfa, fak):
                fak = input(">>> Fakultet: ")
            kir_yil = int(input(">>> O'qishga kirgan yili: "))
            while not re.match(yil, str(kir_yil)) or t_yil + 17 > kir_yil:
                kir_yil = int(input(">>> O'qishga kirgan yili: "))
            info = Talaba(ism,fam,t_yil,kir_yil, vil, fak)
            x = False
    elif menu == "kurs_kutar":
        info.kurs_kutar()
    elif menu == "kurs_qoldir":
        info.kurs_qoldir()
    elif menu == "ism_uzgar":
        info.ism_uzgar()
    elif menu == "fam_uzgar":
        info.fam_uzgar()
    elif menu == "off":
        a = False
    elif menu == "info":
        print(info.mal())
    else:
        continue

>>> Buyruqlar (new, kurs_kutar, kurs_qoldir, ism_uzgar, fam_uzgar, info, off): off


In [8]:
class Ishchi:
    __ish_soati = 8
    def __init__(self, ism, fam, kasb, stavka, oylik, ish_turi):
        self.__ism = ism
        self.__fam = fam
        self.__kasb = kasb
        self.__stavka = stavka
        self.__oylik = oylik
        self.__ish_turi = ish_turi
    def get_info(self):
        return f"{self.__ism} {self.__fam} ismli ishchi {self.__kasb} sohasida {self.__ish_turi}da {self.__stavka} ishlab \
{self.__oylik} so'm oladi"
    def set_kasb(self, kasb, stavka, oylik, ish_turi):
        self.__kasb = kasb
        self.__stavka = stavka
        self.__oylik = oylik
        self.__ish_turi = ish_turi
    def get_soati(self):
        return Ishchi.__ish_soati*self.__stavka
xursand = Ishchi("Xursand", "Sobirov", "Dasturchi", 1, 10000000, "doimiy")
print(xursand.get_info())
print("Ish soati: ", xursand.get_soati())
xursand.set_kasb("Suniy Intellekt", 0.5, 20000000, "Frilance")
print(xursand.get_info())
print("Ish soati: ", xursand.get_soati())

Xursand Sobirov ismli ishchi Dasturchi sohasida doimiyda 1 ishlab 10000000 so'm oladi
Ish soati:  8
Xursand Sobirov ismli ishchi Suniy Intellekt sohasida Frilanceda 0.5 ishlab 20000000 so'm oladi
Ish soati:  4.0


In [9]:
from tkinter import *       
from tkinter import messagebox       
from tkinter.ttk import *
class Telefonlar:
    def __init__(self, brand, model, narx, dioganal, ekran, kamera, old_kamera, protsessor, ram, xotira, batareyka, protsessor_chastotasi):
        self.__brand = brand
        self.__model = model
        self.__narx = narx
        self.__dioganal = dioganal
        self.__ekran = ekran
        self.__kamera = kamera
        self.__old_kamera = old_kamera
        self.__protsessor = protsessor
        self.__ram = ram
        self.__xotira = xotira
        self.__batareyka = batareyka
        self.__protsessor_chastotasi = protsessor_chastotasi
    def get_info(self):
        return f"Brendi: \t\t\t\t{self.__brand}\nModeli: \t\t\t\t{self.__model}\nNarxi($): \t\t\t\t{self.__narx}\nEkran dioganali(dyum): \t\t{self.__dioganal}\n\
Ekran o'lchami: \t\t\t{self.__ekran}\nAsosiy kamera(Mp): \t\t{self.__kamera}\nOld kamera(Mp): \t\t\t{self.__old_kamera}\n\
Protsessor: \t\t\t{self.__protsessor}\nRAM(Gb): \t\t\t{self.__ram}\nDoimiy xotira(Gb): \t\t{self.__xotira}\nQuvvati(mAh): \t\t\t{self.__batareyka}\n\
Protsessor chastotasi(MHz): \t{self.__protsessor_chastotasi}"
    def update_narx(self,y_n):
        #n = int(input("Yangi narx: "))
        self.__narx = y_n
    def get_soati(self):
        return Telefonlar.__ish_soati*self.__stavka
redmi = Telefonlar("Redmi", "Note 11 pro", 300, 6.67,"2400 × 1080","108 + 8 + 2", 16, "Qualcomm Snapdragon 695", 8, 128, 5000, 2200)
samsung = Telefonlar("Samsung", "Galaxy S22 ultra", 400, 6.8,"3088 × 1440","108 + 10 + 10 + 12", 40, "Samsung Exynos 2200", 8, 128, 5000, 2800)
iphone = Telefonlar("Iphone", "13 Pro max", 1200, 6.1,"1284 × 2778","12 + 12 + 12", 12, "Apple A15 Bionic", 6, 128, 4352, 3200)
# print(redmi.get_info())
# print(samsung.get_info())

root = Tk()
root.title("Mobil telefonlar")
root.geometry("200x100")
def _redmi():
    messagebox.showinfo('Redmi Note 11 pro', redmi.get_info())

def edit():
    newWindow = Toplevel(root)
    y_n = Entry(newWindow)
    junat = Button(newWindow, text = "Narxni o'zgartirish", command=redmi.update_narx(y_n))
    y_n.pack()
    junat.pack()
def _samsung():
    messagebox.showinfo('Samsung S22 Ultra', samsung.get_info())
def _iphone():
    messagebox.showinfo('Iphone 13 Pro max', iphone.get_info())
    
btn = Button(root, text = "Redmi", command = _redmi)
btnr = Button(root, text = "Narx o'zgartirish", command = edit)
btn1 = Button(root, text = "Samsung", command = _samsung)
btns = Button(root, text = "Narx o'zgartirish", command = samsung.update_narx)
btn2 = Button(root, text = "Iphone", command = _iphone)
btni = Button(root, text = "Narx o'zgartirish", command = iphone.update_narx)
btnexit = Button(root, text = 'Chiqish', command = root.destroy)

   
btn.place(x=0, y=0)
btnr.place(x=100, y=0)
btn1.place(x=0, y=25)
btns.place(x=100, y=25)
btn2.place(x=0, y=50)
btni.place(x=100, y=50)
btnexit.pack(side = 'bottom') 
 
root.mainloop()

In [10]:
from tkinter import *
 
root = Tk()
root.title("App")
root.geometry("350x300")

def _redmi():
    label.config(
     text = redmi.get_info()
   )
def _samsung():
    label.config(
     text = samsung.get_info()
   )

button = Button(
  text="Redmi",
  command=_redmi
)
button1 = Button(
  text="Samsung",
  command=_samsung
)
button.pack(side="top")
button1.pack(side="top")
 
label = Label(
  text="...", justify=LEFT
)
label.pack()
 
root.mainloop()

In [11]:
# Sistema
import re

viloyatlar = ["Toshkent", "Andijon", "Farg'ona", "Namangan", "Sirdaryo", "Jizzax", "Samarqand", "Qashqadaryo",
              "Surxondaryo", "Navoiy", "Buxoro", "Xorazm", "Qoraqalpog'iston"]

class Ishchilar:
    __mhtekm = 900000
    def __init__(self, ism, fam, t_yil, jins, vil, razryad, malumot, pasport, kasbi, ish_tajriba, aloqa, lavozim):
        self.__ism = ism
        self.__fam = fam
        self.__t_yil = t_yil
        self.__jins = jins
        self.__vil = vil
        self.__raz = razryad
        self.__malumot = malumot
        self.__pasport = pasport
        self.__kasbi = kasbi
        self.__ish_taj = ish_tajriba
        self.__aloqa = aloqa
        self.__lavozim = lavozim
        self.__oylik = Ishchilar.__mhtekm * self.__raz
    # Ishchi ma'lumotlari
    def get_info(self):
        return f"Ismi: {self.__ism} \nFamiliyasi: {self.__fam} \nTug'ilgan yili: {self.__t_yil} \nJinsi: {self.__jins} \
\nViloyati: {self.__vil} \nIsh razryadi: {self.__raz} \nMa'lumoti: {self.__malumot} \nPasporti: {self.__pasport} \
\nKasbi: {self.__kasbi} \nIsh tajribasi: {self.__ish_taj} \nAloqa: {self.__aloqa} \nLavozimi: {self.__lavozim} \nOylik maoshi: {self.__oylik}"
    def get_money(self):
        return self.__oylik
    def update_isfam(self):
        isfa = r"[A-Z]{1}[a-z']+$"
            
        yangi_ism = input(">>> Ism: ")
        while not re.match(isfa, yangi_ism):
            yangi_ism = input(">>> Ism: ")
                
        yangi_fam = input(">>> Familiya: ")
        while not re.match(isfa, yangi_fam):
            yangi_fam = input(">>> Familiya: ")   
        self.__ism = yangi_ism
        self.__fam = yangi_fam
    def update_raz(self):
        yangi_razryad = int(input(">>> Razryadi: "))
        while not re.match(r"\d+$", str(yangi_razryad)):
            yangi_razryad = input(">>> Razryadi: ")
        self.__raz = yangi_razryad
        self.__oylik = Ishchilar.__mhtekm * self.__raz
    def update_pasport(self):
        yangi_pasport = input(">>> Pasport seriya va raqami(AA1234567): ")
        while not re.match(r"[A-Z]{2}[0-9]{7}$", yangi_pasport):
            yangi_pasport = input(">>> Pasport seriya va raqami(AA1234567): ")
        self.__pasport = yangi_pasport
    def update_aloqa(self):
        yangi_aloqa = input(">>> Telefon raqami(XXX-XX-XX): ")
        while not re.match(r"[0-9]{3}-[0-9]{2}-[0-9]{2}", yangi_aloqa):
            yangi_aloqa = input(">>> Telefon raqami(XXX-XX-XX): ")
        self.__aloqa = yangi_aloqa
    def update_lavozim(self):
        yangi_lavozim = input(">>> Lavozimi: ")
        while not re.match(isfa, yangi_lavozim):
            yangi_lavozim = input(">>> Lavozimi: ")
        self.__lavozim = yangi_lavozim

# Menyu
a = True
while a:
    menu = input(">>> Buyruqlar (new, info, oylik, ism_fam_uzgar, razryad_uzgar, lavozim_uzgar, aloqa_uzgar, off): ")
    # Talaba ma'lumotlarini kiritish
    if menu == "new":
        x = True
        while x:
            isfa = r"[A-Z]{1}[a-z']+$"
            yil = r"(19|20)[0-9]{2}"
            
            ism = input(">>> Ism: ")
            while not re.match(isfa, ism):
                ism = input(">>> Ism: ")
                
            fam = input(">>> Familiya: ")
            while not re.match(isfa, fam):
                fam = input(">>> Familiya: ")
                
            t_yil = int(input(">>> Tug'ilgan yil(Yil): "))
            while not re.match(yil, str(t_yil)):
                t_yil = int(input(">>> Tug'ilgan yil(yil): "))
                
            jins = input(">>> Jinsi(Erkak/Ayol): ")
            while not re.match(r"(Erkak|Ayol)$", jins):
                jins = input(">>> Jinsi(Erkak/Ayol): ")
                
            vil = input(">>> Viloyati: ")
            while vil not in viloyatlar:
                vil = input(">>> Viloyati: ")
                
            razryad = int(input(">>> Razryadi: "))
            while not re.match(r"\d+$", str(razryad)):
                razryad = input(">>> Razryadi: ")
                
            malumot = input(">>> Ma'lumoti: ")
            while not re.match(isfa, malumot):
                malumot = input(">>> Ma'lumoti: ")
            
            pasport = input(">>> Pasport seriya va raqami(AA1234567): ")
            while not re.match(r"[A-Z]{2}[0-9]{7}$", pasport):
                pasport = input(">>> Pasport seriya va raqami(AA1234567): ")
                
            kasbi = input(">>> Kasbi: ")
            while not re.match(isfa, kasbi):
                kasbi = input(">>> Kasbi: ")
                
            lavozim = input(">>> Lavozimi: ")
            while not re.match(isfa, lavozim):
                lavozim = input(">>> Lavozimi: ")
                
            ish_tajriba = int(input(">>> Ish tajribasi(Yil): "))
            while not re.match(r"\d+", str(ish_tajriba)):
                ish_tajriba = input(">>> Ish tajribasi(Yil): ")
            
            aloqa = input(">>> Telefon raqami(XXX-XX-XX): ")
            while not re.match(r"[0-9]{3}-[0-9]{2}-[0-9]{2}", aloqa):
                aloqa = input(">>> Telefon raqami(XXX-XX-XX): ")
                
            kirit = Ishchilar(ism,fam,t_yil, jins, vil, razryad, malumot, pasport, kasbi, ish_tajriba, aloqa, lavozim)
            
            x = False
    elif menu == "razryad_uzgar":
        kirit.update_raz()
    elif menu == "oylik":
        print(kirit.get_money())
    elif menu == "ism_fam_uzgar":
        kirit.update_isfam()
    elif menu == "lavozim_uzgar":
        kirit.update_lavozim()
    elif menu == "aloqa_uzgar":
        kirit.update_aloqa()
    elif menu == "off":
        a = False
    elif menu == "info":
        print(kirit.get_info())
    else:
        continue

>>> Buyruqlar (new, info, oylik, ism_fam_uzgar, razryad_uzgar, lavozim_uzgar, aloqa_uzgar, off): off


In [12]:
import json

#     def get_ishchilar(self):
#         sikl = len(temp)
#         for i in range(sikl):
#             print(f"Ismi: {temp[i]["ism"]} \nFamiliyasi: {temp[i]["familiya"]} \nTug'ilgan yili: {temp[i]["t_yil"]} \nJinsi: {temp[i]["jins"]} \
# \nViloyati: {temp[i]["viloyat"]} \nIsh razryadi: {temp[i]["razryad"]} \nMa'lumoti: {temp[i]["malumot"]} \nPasporti: {temp[i]["pasport"]} \
# \nKasbi: {temp[i]["kasbi"]} \nIsh tajribasi: {temp[i]["ish_tajriba"]} \nAloqa: {temp[i]["aloqa"]} \nOylik maoshi: {temp[i]["oylik"]}")


def write_json(data, filename="baza.json"):
    with open(filename, "w") as f_w:
        json.dump(data, f_w, indent=4)

with open("baza.json") as f_r:
    data = json.load(f_r)
    temp = data["ishchilar"]
a = ism+"_"+fam:{"ism": ism, "familiya": fam, "t_yil":t_yil, "jins": jins "viloyat": vil, "razryad": razryad, "malumot": malumot, "pasport":pasport, "kasbi": kasbi, "ish_tajriba":ish_tajriba, "aloqa": aloqa, "oylik": kirit.get_money()}
if temp.count(a) == 0:
    temp.append(a)
if temp.count(a) > 1:
    for _ in range(temp.count(a)-1):
        temp.remove(a)
write_json(data)

SyntaxError: invalid syntax (2230470869.py, line 18)

In [ ]:
import json
ism = input("Ismi: ")
fam = input("Familiya: ")
yosh = int(input("Yoshi: "))
def write_json(data, filename="baza1.json"):
    with open(filename, "w") as f_w:
        json.dump(data, f_w, indent=4)

with open("baza1.json") as f:
    data = json.load(f)
    temp = data["ishchilar"]

a = {ism+"_"+fam:{"ism": ism, "familiya": fam, "yosh": yosh}}
if temp.count(a) == 0:
    temp.append(a)
if temp.count(a) > 1:
    for _ in range(temp.count(a)-1):
        temp.remove(a)
print(temp.index(a))
write_json(data)
for i in range(len(temp)):
    print(temp[i]["ism"])

In [ ]:

with open("baza.json") as f_r:
    data = json.load(f_r)
    temp = data["ishchilar"]
print(temp[0]["ism"])
print(len(temp))

In [ ]:
def get(self):
    return [x for x in dir(self) if not x.startswith('__')]
print(get(a))

In [ ]:
# Uyga vazifa
fanlar = ["Dasturlash", "Algebra", "Geometrya"]
class Talaba:
    def __init__(self, ism, fan):
        self.ism = ism
        self.fan = fan
    
class Fan(Talaba):
    tal = []
    def __init__(self, ism, fan, fanlar):
        super().__init__(ism, fan)
        self.fanlar = fanlar
    def dasturlash(self):
        if self.fan == self.fanlar:
            tal.append(self.ism)
        return tal


talaba_1 = Talaba("Abdulla", "Dasturlash")
talaba_2 = Talaba("Ahmad", "Dasturlash")
talaba_3 = Talaba("Asror", "Algebra")
fan_1 = Fan(fanlar)
print(fan_1.dasturlash())

In [ ]:
!pip install numpy

In [ ]:
!pip install --upgrade pip

In [ ]:
%time [i for i in range(1000)]

In [8]:
import numpy as np
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
print(a.size)

9


In [11]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
b = np.ones((4,4,4))

In [14]:
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [43]:
c = np.ones((4,4), dtype=np.uint8)

In [44]:
print(c)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [39]:
x = np.ones_like(a)

In [40]:
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [53]:
np_3d = np.arange(18).reshape(3,2,3)
print(np_3d)
print()
print(np_3d[2,:,1:])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]

[[13 14]
 [16 17]]


In [52]:
np_2 = np.random.randint(1,9,size=(10,10))
np_2

array([[1, 6, 2, 2, 2, 4, 3, 2, 7, 4],
       [3, 4, 3, 6, 5, 7, 4, 6, 3, 6],
       [5, 7, 6, 1, 8, 4, 3, 7, 8, 6],
       [8, 3, 1, 4, 8, 3, 2, 2, 5, 8],
       [5, 7, 7, 2, 1, 3, 5, 8, 1, 8],
       [4, 2, 2, 3, 2, 3, 6, 1, 7, 2],
       [2, 8, 7, 4, 1, 2, 1, 5, 4, 1],
       [6, 4, 4, 3, 1, 1, 2, 3, 5, 6],
       [7, 8, 4, 7, 6, 1, 4, 4, 8, 4],
       [5, 4, 3, 3, 7, 1, 7, 6, 5, 5]])

In [53]:
np_2[2:8,2:8] = 0

In [54]:
np_2

array([[1, 6, 2, 2, 2, 4, 3, 2, 7, 4],
       [3, 4, 3, 6, 5, 7, 4, 6, 3, 6],
       [5, 7, 0, 0, 0, 0, 0, 0, 8, 6],
       [8, 3, 0, 0, 0, 0, 0, 0, 5, 8],
       [5, 7, 0, 0, 0, 0, 0, 0, 1, 8],
       [4, 2, 0, 0, 0, 0, 0, 0, 7, 2],
       [2, 8, 0, 0, 0, 0, 0, 0, 4, 1],
       [6, 4, 0, 0, 0, 0, 0, 0, 5, 6],
       [7, 8, 4, 7, 6, 1, 4, 4, 8, 4],
       [5, 4, 3, 3, 7, 1, 7, 6, 5, 5]])

In [3]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def myfunc(self):
        return f"My name is {self.name}"

name = input()
age = input()
pers = Person(name, age)
print(pers.myfunc())

Xursand
30
My name is Xursand


In [27]:
import numpy as np
n = int(input())
np = np.ones((n,n), dtype=np.uint8)
i = 0
for i in range(n):
    for j in range(n):
        m = int(input())
        np[j,-i+1] = m
print(np)

2
1
2
3
4
[[3 1]
 [4 2]]


## 